@isTest 
public with sharing class TestCoverageBufferTest {

	 @isTest
  public static void test(){
    TestCoverageBuffer.calculate();
    TestCoverageBuffer.calculate2();
    TestCoverageBuffer.calculate3();
    TestCoverageBuffer.calculate4();
    TestCoverageBuffer.calculate5();
    TestCoverageBuffer.calculate6();
    TestCoverageBuffer.calculate7();
    TestCoverageBuffer.calculate8();
    TestCoverageBuffer.calculate9();
 //   TestCoverageBuffer.calculate10();
    TestCoverageBuffer.calculate11();
    TestCoverageBuffer.calculate12();
 //   TestCoverageBuffer.calculate13();
    TestCoverageBuffer.calculate14();
    TestCoverageBuffer.calculate15();
    TestCoverageBuffer.calculate16();
    TestCoverageBuffer.calculate17();
    TestCoverageBuffer.calculate18();
    TestCoverageBuffer.calculate19();
    TestCoverageBuffer.calculate20();
    TestCoverageBuffer.calculate21();
    TestCoverageBuffer.calculateA1();
	TestCoverageBuffer.calculateA2();
	TestCoverageBuffer.calculateA3();
	TestCoverageBuffer.calculateA4();
    TestCoverageBuffer.calculateA21();
	TestCoverageBuffer.calculateA22();
	TestCoverageBuffer.calculateA23();
  }
}